### ISSUE TITLE
Polymorphic keys and values

### ISSUE THREAD

**Issue by struktured** [smondet/trakeva#10]
Is it by design that this library works with raw string keys and values?

**Comment by smondet** [comment]
The backends understand only strings (git, sqlite, more to come), it would be nice maybe to support char-bigarrays, but polymorphic keys and values would have to come with ``( 'a -> string, string -> 'a option)`` functions anyway, right?

I think it's better to have the (de)serialization at a higher level than what Trakeva provides (e.g. for domain-specific errors messages, and clever re-use of serialized strings).

Which use case did you have in mind?

**Comment by struktured** [comment]
I am using riak as a key/value store for maintaining probability distributions in [ocaml-prob-cache](https://github.com/struktured/ocaml-prob-cache). It would be interesting to abstract the key/value store layer, but in my case they are complex ocaml types (with serializers being carried around, as you mentioned). 

The cache stores I'm considering abstracting over, for example, are riak, hazelcast, coherence, sql dbs, and a vanilla in memory version. You're probably right that if it's worth doing at all it likely deserves to be it's own type of abstraction.

Thanks
