### ISSUE TITLE
Publish new version of trakeva

### ISSUE THREAD

**Issue by ihodes** [smondet/trakeva#26]
So trakeva_of_uri can be opam installed easily

**Comment by smondet** [comment]
One it's way https://github.com/smondet/trakeva/releases/tag/trakeva.0.1.0

**Comment by smondet** [comment]
And https://github.com/ocaml/opam-repository/pull/5586

**Comment by smondet** [comment]
And the doc : http://seb.mondet.org/software/trakeva/trakeva.0.1.0/index.html
